/**
 * OrderCloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OrderCloud);
  }
}(this, function(expect, OrderCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OrderCloud.AddressApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AddressApi', function() {
    describe('buyersBuyerIDAddressesAddressIDAssignmentsDelete', function() {
      it('should call buyersBuyerIDAddressesAddressIDAssignmentsDelete successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDAddressesAddressIDAssignmentsDelete
        //instance.buyersBuyerIDAddressesAddressIDAssignmentsDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDAddressesAddressIDDelete', function() {
      it('should call buyersBuyerIDAddressesAddressIDDelete successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDAddressesAddressIDDelete
        //instance.buyersBuyerIDAddressesAddressIDDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDAddressesAddressIDGet', function() {
      it('should call buyersBuyerIDAddressesAddressIDGet successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDAddressesAddressIDGet
        //instance.buyersBuyerIDAddressesAddressIDGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDAddressesAddressIDPatch', function() {
      it('should call buyersBuyerIDAddressesAddressIDPatch successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDAddressesAddressIDPatch
        //instance.buyersBuyerIDAddressesAddressIDPatch(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDAddressesAddressIDPut', function() {
      it('should call buyersBuyerIDAddressesAddressIDPut successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDAddressesAddressIDPut
        //instance.buyersBuyerIDAddressesAddressIDPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDAddressesAssignmentsGet', function() {
      it('should call buyersBuyerIDAddressesAssignmentsGet successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDAddressesAssignmentsGet
        //instance.buyersBuyerIDAddressesAssignmentsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDAddressesAssignmentsPost', function() {
      it('should call buyersBuyerIDAddressesAssignmentsPost successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDAddressesAssignmentsPost
        //instance.buyersBuyerIDAddressesAssignmentsPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDAddressesGet', function() {
      it('should call buyersBuyerIDAddressesGet successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDAddressesGet
        //instance.buyersBuyerIDAddressesGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDAddressesPost', function() {
      it('should call buyersBuyerIDAddressesPost successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDAddressesPost
        //instance.buyersBuyerIDAddressesPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
