/**
 * OrderCloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OrderCloud);
  }
}(this, function(expect, OrderCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OrderCloud.AdminAddressApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AdminAddressApi', function() {
    describe('addressesAddressIDDelete', function() {
      it('should call addressesAddressIDDelete successfully', function(done) {
        //uncomment below and update the code to test addressesAddressIDDelete
        //instance.addressesAddressIDDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addressesAddressIDGet', function() {
      it('should call addressesAddressIDGet successfully', function(done) {
        //uncomment below and update the code to test addressesAddressIDGet
        //instance.addressesAddressIDGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addressesAddressIDPatch', function() {
      it('should call addressesAddressIDPatch successfully', function(done) {
        //uncomment below and update the code to test addressesAddressIDPatch
        //instance.addressesAddressIDPatch(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addressesAddressIDPut', function() {
      it('should call addressesAddressIDPut successfully', function(done) {
        //uncomment below and update the code to test addressesAddressIDPut
        //instance.addressesAddressIDPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addressesGet', function() {
      it('should call addressesGet successfully', function(done) {
        //uncomment below and update the code to test addressesGet
        //instance.addressesGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addressesPost', function() {
      it('should call addressesPost successfully', function(done) {
        //uncomment below and update the code to test addressesPost
        //instance.addressesPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
