/**
 * OrderCloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OrderCloud);
  }
}(this, function(expect, OrderCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OrderCloud.AdminUserGroupApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AdminUserGroupApi', function() {
    describe('usergroupsAssignmentsGet', function() {
      it('should call usergroupsAssignmentsGet successfully', function(done) {
        //uncomment below and update the code to test usergroupsAssignmentsGet
        //instance.usergroupsAssignmentsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('usergroupsAssignmentsPost', function() {
      it('should call usergroupsAssignmentsPost successfully', function(done) {
        //uncomment below and update the code to test usergroupsAssignmentsPost
        //instance.usergroupsAssignmentsPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('usergroupsGet', function() {
      it('should call usergroupsGet successfully', function(done) {
        //uncomment below and update the code to test usergroupsGet
        //instance.usergroupsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('usergroupsPost', function() {
      it('should call usergroupsPost successfully', function(done) {
        //uncomment below and update the code to test usergroupsPost
        //instance.usergroupsPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('usergroupsUserGroupIDAssignmentsUserIDDelete', function() {
      it('should call usergroupsUserGroupIDAssignmentsUserIDDelete successfully', function(done) {
        //uncomment below and update the code to test usergroupsUserGroupIDAssignmentsUserIDDelete
        //instance.usergroupsUserGroupIDAssignmentsUserIDDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('usergroupsUserGroupIDDelete', function() {
      it('should call usergroupsUserGroupIDDelete successfully', function(done) {
        //uncomment below and update the code to test usergroupsUserGroupIDDelete
        //instance.usergroupsUserGroupIDDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('usergroupsUserGroupIDGet', function() {
      it('should call usergroupsUserGroupIDGet successfully', function(done) {
        //uncomment below and update the code to test usergroupsUserGroupIDGet
        //instance.usergroupsUserGroupIDGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('usergroupsUserGroupIDPatch', function() {
      it('should call usergroupsUserGroupIDPatch successfully', function(done) {
        //uncomment below and update the code to test usergroupsUserGroupIDPatch
        //instance.usergroupsUserGroupIDPatch(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('usergroupsUserGroupIDPut', function() {
      it('should call usergroupsUserGroupIDPut successfully', function(done) {
        //uncomment below and update the code to test usergroupsUserGroupIDPut
        //instance.usergroupsUserGroupIDPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
