/**
 * OrderCloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OrderCloud);
  }
}(this, function(expect, OrderCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OrderCloud.ApprovalRuleApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApprovalRuleApi', function() {
    describe('buyersBuyerIDApprovalrulesApprovalRuleIDDelete', function() {
      it('should call buyersBuyerIDApprovalrulesApprovalRuleIDDelete successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDApprovalrulesApprovalRuleIDDelete
        //instance.buyersBuyerIDApprovalrulesApprovalRuleIDDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDApprovalrulesApprovalRuleIDGet', function() {
      it('should call buyersBuyerIDApprovalrulesApprovalRuleIDGet successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDApprovalrulesApprovalRuleIDGet
        //instance.buyersBuyerIDApprovalrulesApprovalRuleIDGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDApprovalrulesApprovalRuleIDPatch', function() {
      it('should call buyersBuyerIDApprovalrulesApprovalRuleIDPatch successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDApprovalrulesApprovalRuleIDPatch
        //instance.buyersBuyerIDApprovalrulesApprovalRuleIDPatch(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDApprovalrulesApprovalRuleIDPut', function() {
      it('should call buyersBuyerIDApprovalrulesApprovalRuleIDPut successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDApprovalrulesApprovalRuleIDPut
        //instance.buyersBuyerIDApprovalrulesApprovalRuleIDPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDApprovalrulesGet', function() {
      it('should call buyersBuyerIDApprovalrulesGet successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDApprovalrulesGet
        //instance.buyersBuyerIDApprovalrulesGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDApprovalrulesPost', function() {
      it('should call buyersBuyerIDApprovalrulesPost successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDApprovalrulesPost
        //instance.buyersBuyerIDApprovalrulesPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
