/**
 * OrderCloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OrderCloud);
  }
}(this, function(expect, OrderCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OrderCloud.LineItemApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LineItemApi', function() {
    describe('buyersBuyerIDOrdersOrderIDLineitemsGet', function() {
      it('should call buyersBuyerIDOrdersOrderIDLineitemsGet successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDLineitemsGet
        //instance.buyersBuyerIDOrdersOrderIDLineitemsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDLineitemsLineItemIDDelete', function() {
      it('should call buyersBuyerIDOrdersOrderIDLineitemsLineItemIDDelete successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDLineitemsLineItemIDDelete
        //instance.buyersBuyerIDOrdersOrderIDLineitemsLineItemIDDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDLineitemsLineItemIDGet', function() {
      it('should call buyersBuyerIDOrdersOrderIDLineitemsLineItemIDGet successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDLineitemsLineItemIDGet
        //instance.buyersBuyerIDOrdersOrderIDLineitemsLineItemIDGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDLineitemsLineItemIDPatch', function() {
      it('should call buyersBuyerIDOrdersOrderIDLineitemsLineItemIDPatch successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDLineitemsLineItemIDPatch
        //instance.buyersBuyerIDOrdersOrderIDLineitemsLineItemIDPatch(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDLineitemsLineItemIDPut', function() {
      it('should call buyersBuyerIDOrdersOrderIDLineitemsLineItemIDPut successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDLineitemsLineItemIDPut
        //instance.buyersBuyerIDOrdersOrderIDLineitemsLineItemIDPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDLineitemsLineItemIDShiptoPatch', function() {
      it('should call buyersBuyerIDOrdersOrderIDLineitemsLineItemIDShiptoPatch successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDLineitemsLineItemIDShiptoPatch
        //instance.buyersBuyerIDOrdersOrderIDLineitemsLineItemIDShiptoPatch(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDLineitemsLineItemIDShiptoPut', function() {
      it('should call buyersBuyerIDOrdersOrderIDLineitemsLineItemIDShiptoPut successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDLineitemsLineItemIDShiptoPut
        //instance.buyersBuyerIDOrdersOrderIDLineitemsLineItemIDShiptoPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDLineitemsPost', function() {
      it('should call buyersBuyerIDOrdersOrderIDLineitemsPost successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDLineitemsPost
        //instance.buyersBuyerIDOrdersOrderIDLineitemsPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
