/**
 * OrderCloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OrderCloud);
  }
}(this, function(expect, OrderCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OrderCloud.OrderApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrderApi', function() {
    describe('buyersBuyerIDOrdersOrderIDApprovalsGet', function() {
      it('should call buyersBuyerIDOrdersOrderIDApprovalsGet successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDApprovalsGet
        //instance.buyersBuyerIDOrdersOrderIDApprovalsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDApprovePost', function() {
      it('should call buyersBuyerIDOrdersOrderIDApprovePost successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDApprovePost
        //instance.buyersBuyerIDOrdersOrderIDApprovePost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDBilltoPatch', function() {
      it('should call buyersBuyerIDOrdersOrderIDBilltoPatch successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDBilltoPatch
        //instance.buyersBuyerIDOrdersOrderIDBilltoPatch(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDBilltoPut', function() {
      it('should call buyersBuyerIDOrdersOrderIDBilltoPut successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDBilltoPut
        //instance.buyersBuyerIDOrdersOrderIDBilltoPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDCancelPost', function() {
      it('should call buyersBuyerIDOrdersOrderIDCancelPost successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDCancelPost
        //instance.buyersBuyerIDOrdersOrderIDCancelPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDDeclinePost', function() {
      it('should call buyersBuyerIDOrdersOrderIDDeclinePost successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDDeclinePost
        //instance.buyersBuyerIDOrdersOrderIDDeclinePost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDDelete', function() {
      it('should call buyersBuyerIDOrdersOrderIDDelete successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDDelete
        //instance.buyersBuyerIDOrdersOrderIDDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDEligibleapproversGet', function() {
      it('should call buyersBuyerIDOrdersOrderIDEligibleapproversGet successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDEligibleapproversGet
        //instance.buyersBuyerIDOrdersOrderIDEligibleapproversGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDGet', function() {
      it('should call buyersBuyerIDOrdersOrderIDGet successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDGet
        //instance.buyersBuyerIDOrdersOrderIDGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDPatch', function() {
      it('should call buyersBuyerIDOrdersOrderIDPatch successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDPatch
        //instance.buyersBuyerIDOrdersOrderIDPatch(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDPromotionsGet', function() {
      it('should call buyersBuyerIDOrdersOrderIDPromotionsGet successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDPromotionsGet
        //instance.buyersBuyerIDOrdersOrderIDPromotionsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDPromotionsPromoCodeDelete', function() {
      it('should call buyersBuyerIDOrdersOrderIDPromotionsPromoCodeDelete successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDPromotionsPromoCodeDelete
        //instance.buyersBuyerIDOrdersOrderIDPromotionsPromoCodeDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDPromotionsPromoCodePost', function() {
      it('should call buyersBuyerIDOrdersOrderIDPromotionsPromoCodePost successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDPromotionsPromoCodePost
        //instance.buyersBuyerIDOrdersOrderIDPromotionsPromoCodePost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDPut', function() {
      it('should call buyersBuyerIDOrdersOrderIDPut successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDPut
        //instance.buyersBuyerIDOrdersOrderIDPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDShipPost', function() {
      it('should call buyersBuyerIDOrdersOrderIDShipPost successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDShipPost
        //instance.buyersBuyerIDOrdersOrderIDShipPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDShiptoPatch', function() {
      it('should call buyersBuyerIDOrdersOrderIDShiptoPatch successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDShiptoPatch
        //instance.buyersBuyerIDOrdersOrderIDShiptoPatch(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDShiptoPut', function() {
      it('should call buyersBuyerIDOrdersOrderIDShiptoPut successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDShiptoPut
        //instance.buyersBuyerIDOrdersOrderIDShiptoPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDSubmitPost', function() {
      it('should call buyersBuyerIDOrdersOrderIDSubmitPost successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDSubmitPost
        //instance.buyersBuyerIDOrdersOrderIDSubmitPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersPost', function() {
      it('should call buyersBuyerIDOrdersPost successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersPost
        //instance.buyersBuyerIDOrdersPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersPut', function() {
      it('should call buyersBuyerIDOrdersPut successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersPut
        //instance.buyersBuyerIDOrdersPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ordersIncomingGet', function() {
      it('should call ordersIncomingGet successfully', function(done) {
        //uncomment below and update the code to test ordersIncomingGet
        //instance.ordersIncomingGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ordersOutgoingGet', function() {
      it('should call ordersOutgoingGet successfully', function(done) {
        //uncomment below and update the code to test ordersOutgoingGet
        //instance.ordersOutgoingGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
