/**
 * OrderCloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OrderCloud);
  }
}(this, function(expect, OrderCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OrderCloud.PaymentApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PaymentApi', function() {
    describe('buyersBuyerIDOrdersOrderIDPaymentsGet', function() {
      it('should call buyersBuyerIDOrdersOrderIDPaymentsGet successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDPaymentsGet
        //instance.buyersBuyerIDOrdersOrderIDPaymentsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDPaymentsPaymentIDDelete', function() {
      it('should call buyersBuyerIDOrdersOrderIDPaymentsPaymentIDDelete successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDPaymentsPaymentIDDelete
        //instance.buyersBuyerIDOrdersOrderIDPaymentsPaymentIDDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDPaymentsPaymentIDGet', function() {
      it('should call buyersBuyerIDOrdersOrderIDPaymentsPaymentIDGet successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDPaymentsPaymentIDGet
        //instance.buyersBuyerIDOrdersOrderIDPaymentsPaymentIDGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDPaymentsPaymentIDPatch', function() {
      it('should call buyersBuyerIDOrdersOrderIDPaymentsPaymentIDPatch successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDPaymentsPaymentIDPatch
        //instance.buyersBuyerIDOrdersOrderIDPaymentsPaymentIDPatch(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDPaymentsPaymentIDPut', function() {
      it('should call buyersBuyerIDOrdersOrderIDPaymentsPaymentIDPut successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDPaymentsPaymentIDPut
        //instance.buyersBuyerIDOrdersOrderIDPaymentsPaymentIDPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDPaymentsPaymentIDTransactionsPost', function() {
      it('should call buyersBuyerIDOrdersOrderIDPaymentsPaymentIDTransactionsPost successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDPaymentsPaymentIDTransactionsPost
        //instance.buyersBuyerIDOrdersOrderIDPaymentsPaymentIDTransactionsPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDPaymentsPaymentIDTransactionsTransactionIDDelete', function() {
      it('should call buyersBuyerIDOrdersOrderIDPaymentsPaymentIDTransactionsTransactionIDDelete successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDPaymentsPaymentIDTransactionsTransactionIDDelete
        //instance.buyersBuyerIDOrdersOrderIDPaymentsPaymentIDTransactionsTransactionIDDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDPaymentsPaymentIDTransactionsTransactionIDPatch', function() {
      it('should call buyersBuyerIDOrdersOrderIDPaymentsPaymentIDTransactionsTransactionIDPatch successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDPaymentsPaymentIDTransactionsTransactionIDPatch
        //instance.buyersBuyerIDOrdersOrderIDPaymentsPaymentIDTransactionsTransactionIDPatch(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDPaymentsPaymentIDTransactionsTransactionIDPut', function() {
      it('should call buyersBuyerIDOrdersOrderIDPaymentsPaymentIDTransactionsTransactionIDPut successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDPaymentsPaymentIDTransactionsTransactionIDPut
        //instance.buyersBuyerIDOrdersOrderIDPaymentsPaymentIDTransactionsTransactionIDPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDOrdersOrderIDPaymentsPost', function() {
      it('should call buyersBuyerIDOrdersOrderIDPaymentsPost successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDOrdersOrderIDPaymentsPost
        //instance.buyersBuyerIDOrdersOrderIDPaymentsPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
