/**
 * OrderCloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OrderCloud);
  }
}(this, function(expect, OrderCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OrderCloud.PromotionApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PromotionApi', function() {
    describe('promotionsAssignmentsGet', function() {
      it('should call promotionsAssignmentsGet successfully', function(done) {
        //uncomment below and update the code to test promotionsAssignmentsGet
        //instance.promotionsAssignmentsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('promotionsAssignmentsPost', function() {
      it('should call promotionsAssignmentsPost successfully', function(done) {
        //uncomment below and update the code to test promotionsAssignmentsPost
        //instance.promotionsAssignmentsPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('promotionsGet', function() {
      it('should call promotionsGet successfully', function(done) {
        //uncomment below and update the code to test promotionsGet
        //instance.promotionsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('promotionsPost', function() {
      it('should call promotionsPost successfully', function(done) {
        //uncomment below and update the code to test promotionsPost
        //instance.promotionsPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('promotionsPromotionIDAssignmentsDelete', function() {
      it('should call promotionsPromotionIDAssignmentsDelete successfully', function(done) {
        //uncomment below and update the code to test promotionsPromotionIDAssignmentsDelete
        //instance.promotionsPromotionIDAssignmentsDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('promotionsPromotionIDDelete', function() {
      it('should call promotionsPromotionIDDelete successfully', function(done) {
        //uncomment below and update the code to test promotionsPromotionIDDelete
        //instance.promotionsPromotionIDDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('promotionsPromotionIDGet', function() {
      it('should call promotionsPromotionIDGet successfully', function(done) {
        //uncomment below and update the code to test promotionsPromotionIDGet
        //instance.promotionsPromotionIDGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('promotionsPromotionIDPatch', function() {
      it('should call promotionsPromotionIDPatch successfully', function(done) {
        //uncomment below and update the code to test promotionsPromotionIDPatch
        //instance.promotionsPromotionIDPatch(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('promotionsPromotionIDPut', function() {
      it('should call promotionsPromotionIDPut successfully', function(done) {
        //uncomment below and update the code to test promotionsPromotionIDPut
        //instance.promotionsPromotionIDPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
