/**
 * OrderCloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OrderCloud);
  }
}(this, function(expect, OrderCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OrderCloud.SecurityProfileApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SecurityProfileApi', function() {
    describe('securityprofilesAssignmentsGet', function() {
      it('should call securityprofilesAssignmentsGet successfully', function(done) {
        //uncomment below and update the code to test securityprofilesAssignmentsGet
        //instance.securityprofilesAssignmentsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityprofilesAssignmentsPost', function() {
      it('should call securityprofilesAssignmentsPost successfully', function(done) {
        //uncomment below and update the code to test securityprofilesAssignmentsPost
        //instance.securityprofilesAssignmentsPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityprofilesGet', function() {
      it('should call securityprofilesGet successfully', function(done) {
        //uncomment below and update the code to test securityprofilesGet
        //instance.securityprofilesGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityprofilesSecurityProfileIDAssignmentsDelete', function() {
      it('should call securityprofilesSecurityProfileIDAssignmentsDelete successfully', function(done) {
        //uncomment below and update the code to test securityprofilesSecurityProfileIDAssignmentsDelete
        //instance.securityprofilesSecurityProfileIDAssignmentsDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityprofilesSecurityProfileIDGet', function() {
      it('should call securityprofilesSecurityProfileIDGet successfully', function(done) {
        //uncomment below and update the code to test securityprofilesSecurityProfileIDGet
        //instance.securityprofilesSecurityProfileIDGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
