/**
 * OrderCloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OrderCloud);
  }
}(this, function(expect, OrderCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OrderCloud.ShipmentApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ShipmentApi', function() {
    describe('buyersBuyerIDShipmentsGet', function() {
      it('should call buyersBuyerIDShipmentsGet successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDShipmentsGet
        //instance.buyersBuyerIDShipmentsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDShipmentsPost', function() {
      it('should call buyersBuyerIDShipmentsPost successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDShipmentsPost
        //instance.buyersBuyerIDShipmentsPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDShipmentsShipmentIDDelete', function() {
      it('should call buyersBuyerIDShipmentsShipmentIDDelete successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDShipmentsShipmentIDDelete
        //instance.buyersBuyerIDShipmentsShipmentIDDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDShipmentsShipmentIDGet', function() {
      it('should call buyersBuyerIDShipmentsShipmentIDGet successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDShipmentsShipmentIDGet
        //instance.buyersBuyerIDShipmentsShipmentIDGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDShipmentsShipmentIDItemsOrderIDLineItemIDDelete', function() {
      it('should call buyersBuyerIDShipmentsShipmentIDItemsOrderIDLineItemIDDelete successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDShipmentsShipmentIDItemsOrderIDLineItemIDDelete
        //instance.buyersBuyerIDShipmentsShipmentIDItemsOrderIDLineItemIDDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDShipmentsShipmentIDItemsPost', function() {
      it('should call buyersBuyerIDShipmentsShipmentIDItemsPost successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDShipmentsShipmentIDItemsPost
        //instance.buyersBuyerIDShipmentsShipmentIDItemsPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDShipmentsShipmentIDPatch', function() {
      it('should call buyersBuyerIDShipmentsShipmentIDPatch successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDShipmentsShipmentIDPatch
        //instance.buyersBuyerIDShipmentsShipmentIDPatch(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDShipmentsShipmentIDPut', function() {
      it('should call buyersBuyerIDShipmentsShipmentIDPut successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDShipmentsShipmentIDPut
        //instance.buyersBuyerIDShipmentsShipmentIDPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
