/**
 * OrderCloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OrderCloud);
  }
}(this, function(expect, OrderCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OrderCloud.UserGroupApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserGroupApi', function() {
    describe('buyersBuyerIDUsergroupsAssignmentsGet', function() {
      it('should call buyersBuyerIDUsergroupsAssignmentsGet successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDUsergroupsAssignmentsGet
        //instance.buyersBuyerIDUsergroupsAssignmentsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDUsergroupsAssignmentsPost', function() {
      it('should call buyersBuyerIDUsergroupsAssignmentsPost successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDUsergroupsAssignmentsPost
        //instance.buyersBuyerIDUsergroupsAssignmentsPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDUsergroupsGet', function() {
      it('should call buyersBuyerIDUsergroupsGet successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDUsergroupsGet
        //instance.buyersBuyerIDUsergroupsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDUsergroupsPost', function() {
      it('should call buyersBuyerIDUsergroupsPost successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDUsergroupsPost
        //instance.buyersBuyerIDUsergroupsPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDUsergroupsUserGroupIDAssignmentsUserIDDelete', function() {
      it('should call buyersBuyerIDUsergroupsUserGroupIDAssignmentsUserIDDelete successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDUsergroupsUserGroupIDAssignmentsUserIDDelete
        //instance.buyersBuyerIDUsergroupsUserGroupIDAssignmentsUserIDDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDUsergroupsUserGroupIDDelete', function() {
      it('should call buyersBuyerIDUsergroupsUserGroupIDDelete successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDUsergroupsUserGroupIDDelete
        //instance.buyersBuyerIDUsergroupsUserGroupIDDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDUsergroupsUserGroupIDGet', function() {
      it('should call buyersBuyerIDUsergroupsUserGroupIDGet successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDUsergroupsUserGroupIDGet
        //instance.buyersBuyerIDUsergroupsUserGroupIDGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDUsergroupsUserGroupIDPatch', function() {
      it('should call buyersBuyerIDUsergroupsUserGroupIDPatch successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDUsergroupsUserGroupIDPatch
        //instance.buyersBuyerIDUsergroupsUserGroupIDPatch(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyersBuyerIDUsergroupsUserGroupIDPut', function() {
      it('should call buyersBuyerIDUsergroupsUserGroupIDPut successfully', function(done) {
        //uncomment below and update the code to test buyersBuyerIDUsergroupsUserGroupIDPut
        //instance.buyersBuyerIDUsergroupsUserGroupIDPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
